# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseG1GC -Djdk.attach.allowAttachSelf=true -XX:+EnableDynamicAgentLoading

# Hot reload configuration
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
# Mod Properties
mod_version=1.1.2-1.21.4
maven_group=fun.xingwangzhe
archives_base_name=webmapview
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.119.3+1.21.4
